x-constants:
  backend_host: &backend_host localhost
  backend_port: &backend_port 5000
  db_host: &db_host localhost
  db_port: &db_port 3306
  db_ruser: &db_ruser root
  db_rpass: &db_rpass LaM14PasswordSuperSegreta!!
  db_user: &db_user geocontrol
  db_pass: &db_pass geocontrolpass

services:
  frontend:
    image: smpolito/geocontrolui:latest
    container_name: geocontrol-frontend
    ports:
      - "5173:5173" # Anchored variables defined above (e.g., &frontend_port) cannot be used within quoted strings.
        # Values like port numbers must be written explicitly as literals, but they should remain consistent with the defined variables.
    volumes: # Environment variables for the front-end must be defined in the frontend/env.vars.json and the file must be
      - ./frontend/env-vars.json:/app/dist/config.json # explicitly mounted in the container to be effective

  backend:
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
    image: geocontrol-backend:latest
    container_name: geocontrol-backend
    ports:
      - "5000:5000"
    environment:
      DB_NAME: "mysql"
      DB_TYPE: "mysql"
      DB_HOST: *db_host
      DB_PORT: *db_port
      DB_USERNAME: *db_user
      DB_PASSWORD: *db_pass

  database:
    image: mysql:8
    container_name: geocontrol-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssss
      MYSQL_DATABASE: db
      MYSQL_USER: alessia
      MYSQL_PASSWORD: alessia
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ../data/mysql:/var/lib/mysql:rw
      # ^ Boh la vogliamo la durabilità?