services:
  frontend:
    image: smpolito/geocontrolui:latest
    container_name: geocontrol-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/env-vars.json:/app/dist/config.json

  backend:
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
    image: geocontrol-backend:latest
    container_name: geocontrol-backend
    ports:
      - "5000:5000"
    env_file:
      - .env

  database:
    image: mysql:8
    container_name: geocontrol-db
    ports:
      - "3306:3306"
    env_file:
      - .env
    #volumes:
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql